name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [users, orders, payments, api-gateway]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        run: |
          docker build \
            -t ${{ matrix.service }}-service-test \
            --target test \
            -f services/${{ matrix.service }}/Dockerfile \
            services/${{ matrix.service }}

      - name: Run pytest in container
        run: |
          docker run --rm ${{ matrix.service }}-service-test
